declare module '*.svg';
declare module '*.ttf';
declare module '*.woff';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.css';
declare module '*.scss';
declare module '*.gif';
